### ISSUE TITLE
Copied modules are being deleted every time

### ISSUE THREAD

**Issue by zek** [ConnectyCube/connectycube-js-samples#10]
~~~
npm install -g expo-cli
expo init AwesomeProject
cd AwesomeProject
npm install    ;this one is missed in RN guide
npm install connectycube-reactnative --save
cd node_modules/connectycube-reactnative/xmpp.js
make
cd ../../../
cp -r node_modules/connectycube-reactnative/xmpp.js/node_modules/* node_modules/
~~~

Every time I install new package or when I run run ejected project, the copied modules are being deleted. Are there any way to keep them permanent as a dependency

**Comment by DaveLombardo** [comment]
That's right, 
every time you do `npm install` - then `xmpp.js` is deleted 

The reason why we use this hack with `xmpp.js` is that because we need to use their master, which is not released yet and also because they use sub-packages structure.

Once they release new version we will be able to omit above steps

**Comment by DaveLombardo** [comment]
I have just realized that new version of xmpp.js was released 2 days ago

https://github.com/xmppjs/xmpp.js/releases

I'm going to check it, probably we can remove these annoying stuff

Will let you know

**Comment by zek** [comment]
Thank you @DaveLombardo I was just in pain with it. I installed latest version to test but @xmpp/router dont exists in new version. I guess your library needs also some changes to make it compatible with 0.5.0

**Comment by DaveLombardo** [comment]
I tried to switch to 0.5.0 but have some issues:

- 'events' package not found - fixed
- 'tls' package not found - in prog

**Comment by zek** [comment]
There is also client-core. Did you look at it?

**Comment by DaveLombardo** [comment]
Checking also

I have just realized they changed a lot of stuff :-D
So it needs more time to switch

I think for now it's better to use our current version with that hack

**Comment by zek** [comment]
Can't we just use version 0.3 from npm? There is also a tag but it didn't
work for me. Can you check also the 0.3.0 tag? Or we can also publish
package to npm with the consent of the owner maybe.

**Comment by zek** [comment]
You mean even in native script webrtc is not available?

**Comment by DaveLombardo** [comment]
Yes, right

you can start with Chat and other features for now and later we will push a webrtc support, so you will continue with video chat integration

just tell me what will you use, RN or NS, so we will see what we can do to make it faster

**Comment by zek** [comment]
I will use react native.

Could be cool if you give estimated time for integration.

**Comment by DaveLombardo** [comment]
I guess something like couple of weeks

**Comment by zek** [comment]
@DaveLombardo what about using library below? Is it makes sense to use or not?
https://github.com/aksonov/react-native-xmpp

**Comment by DaveLombardo** [comment]
You can use it, but I do not recommend since you will need to use raw XMPP features
but our lib provides a set of high-level things + documentation, so it's faster in implementation

**Comment by DaveLombardo** [comment]
No, this is a response from a server and not connected to xmpp.js
Could you please raise a separate ticket about WebRTC and give more details what you are doing

**Comment by sonnyp** [comment]
xmpp.js 0.5.1 can now be used on unejected react native apps without fiddling around with modules https://github.com/xmppjs/xmpp.js/releases/tag/v0.5.1

**Comment by DaveLombardo** [comment]
Version 1.4.1 is available
https://www.npmjs.com/package/connectycube-reactnative

it's based on xmpp.js 0.5.2 and now you do not need to do any extra work, just do:

`npm install connectycube-reactnative --save`

@zek
