### ISSUE TITLE
 receive push notifications in react native.

### ISSUE THREAD

**Issue by rajneet-rw** [ConnectyCube/connectycube-js-samples#16]
Please tell me which packages can I use to receive push notifications in react native?

**Comment by ccvlad** [comment]
For first you should subscribe to push notifications ([read](https://developers.connectycube.com/js/push-notifications?id=subscribe)). You able to find information about each parameters [here](https://developers.connectycube.com/js/push-notifications?id=subscribe)

Use [react-native-push-notification](https://www.npmjs.com/package/react-native-push-notification) to receive push notifications.

**Comment by rajneet-rw** [comment]
@ccvlad  what is the client_identification_sequence here
 https://developers.connectycube.com/js/push-notifications?id=subscribe 

any sequence qith unique value ?

**Comment by ccvlad** [comment]
client_identification_sequence - is identifies client device in 3-rd party service like APNS, GCM/FCM. Initially retrieved from 3-rd service and should be send to ConnectyCube to let it send push notifications to the client

https://developers.connectycube.com/server/push_notifications?id=create-subscription

**Comment by DaveLomber** [comment]
Just as additional comment here to @ccvlad comment, about the whole flow:

1st you need to subscribe for push notifications
1) obtain device push token  - use `onRegister` callback here
https://github.com/zo0r/react-native-push-notification#usage
2) then use this `token` to subscribe for push notifications at ConnectyCube side.
Use https://developers.connectycube.com/js/push-notifications?id=subscribe request
where `client_identification_sequence=token`

Then you can send pushes to this subscribed device, via ConnectyCube dashboard or API
Better to try via ConnectyCube dashboard, it's easier to start from here

At client side, to obtain this push, implement the following callback:
https://github.com/zo0r/react-native-push-notification#usage
`onNotification`

That's pretty much about it

**Comment by rajneet-rw** [comment]
@ccvlad  @DaveLomber  thanks for this information .My notifIcations are working now. and I think I have completed my chat system with your package :tada: :tada: and I have really liked your package and the way the team respond to my issues. :blush:
thanks again

**Comment by ccvlad** [comment]
@rajneet-rw , sounds great! Our congratulations!
Thanks for the pleasant words ))
Very glad to help you!

**Comment by DaveLomber** [comment]
@rajneet-rw great ! happy to check your app once you release it!
