### ISSUE TITLE
How to use javascript ConnectyCube api 

### ISSUE THREAD

**Issue by michelepapale1996** [ConnectyCube/connectycube-js-samples#19]
Hi, maybe I'm not getting something, but I don't understand how to use javascript API. Let's consider that I'm building an application in ReactNative and Node.js as WebServer.
My main problem is: every time the client sends a request to my webServer, I have to redo every time the createSession - login phase (in order to insert the request to do to ConnectyCube in the callback of login)?

``` javascript
app.get('/api/chat/:id', (req, res) => {
    const id = req.params.id
    chat.getChat(id)
    res.send("done")
})

getChat: (id) => {
    ConnectyCube.createSession(function(error, session) {
       var userCredentials = {
            'login': "*********",
             'password': "**********"
       };
       ConnectyCube.login(userCredentials, function(error, user){
            //for example, here, I want to create a new dialog
            var params = {
                type: 3,//to create a 1-1 chat
                 occupants_ids: [76774]
            };
            ConnectyCube.chat.dialog.create(params, function(error, conversation) {});
       });
    });
}

**Comment by ccvlad** [comment]
Hi, @michelepapale1996 
Are you trying to execute ConnectyCube.chat.dialog.create() method on server side for each client? Why don't you do it by client side?

**Comment by michelepapale1996** [comment]
Hi @ccvlad, thank you for your answer.
 I've thought to follow this approach in order to have the possibility to (in future) build a web app that uses my rest API. However, also if I execute the ConnectyCube.chat.dialog.create() method client-side, I have to place it in the callback of the login method because of the session token. What am I missing?

**Comment by ccvlad** [comment]
For first I have to understand what you want.
As a client you create session and login to the ConnectyCube REST API server, so your user able to use any API calls.
If you would like to execute any API call from this user on other side, you have to get existed user session (init by session token) or create new and do login (like you did).

Init by session token:
```javascript
// const { ConnectyCube } = require('connectycube');
const ConnectyCube = require('connectycube').ConnectyCube;

const credentials =  = {
    appId: 111,
    authKey: 'aauutthhkkeeyy',
    authSecret: 'sseeccrreett'
}

const config = {
    debug: { mode: 1 }
};

...

const userConnectyCubeInstance = new ConnectyCube();

const userCreds = {
    ...credentials,
    token: sessionToken
}; // pass existed session token to init params 

// or - const userCreds = Object.assign({ token: sessionToken }, credentials); 

userConnectyCubeInstance.init(userCreds, config);
```
So you creates new ConnectyCube instance for each user and init by existed session token instead of ConnectyCube.init + ConnectyCube.createSession + ConnectyCube.login.

Able to use:
```javascript
userConnectyCubeInstance.chat.dialog.create(params, function(error, conversation) {});
```

**Comment by michelepapale1996** [comment]
Really thank you for the answer!
My problem was due to the call of one of the methods you explained (init or init + createSession + login) and immediately later I was calling, for example, userConnectyCubeInstance.chat.dialog.create(params, function(error, conversation) {});

```
ConnectyCube.login(userCredentials, function(error, user){})
ConnectyCube.chat.dialog.create(params, function(error, conversation) {});
```
Following this approach lead me to a not valid token response from the API, while if I write:
```
 ConnectyCube.login(userCredentials, function(error, user){
        ConnectyCube.chat.dialog.create(params, function(error, conversation) {});
  });
```

it works. My problem was due to a lack of knowledge of how callbacks works. 
But now I have another question: I'm building the architecture following your advice: connecting client-side to ConnectyCube. I have a component that has to list all the chats the user has and this is his componentDidMount():
```
componentDidMount(){
        self = this
        ConnectyCube.chat.dialog.list(function(error, dialogs) {
            //here I have all the info I need
            self.setState(blabla)
        });
    }
```
How do you update the state of the component? Calling setState in the callback? Because I would like to do something like this (that, of course, doesn't work):
```

componentDidMount(){
        state = ConnectyCube.chat.dialog.list(function(error, dialogs) {
            //here I have all the info I need
        });
        this.setState(state)
    }
```
Maybe it's not possible and I'm thinking in a synchronous manner, but I cannot figure out it.

**Comment by ccvlad** [comment]
ConnectyCube.chat.dialog.list doesn't return anything, you have to assign all of you need in a body of the callback function.

Try this code:
```javascript
componentDidMount() {
  ConnectyCube.chat.dialog.list((error, result) => {
    this.setState(result.items)
  })
}
```

**Comment by michelepapale1996** [comment]
Okay, thank you very mutch! :)
