### ISSUE TITLE
Using push notifications using ConnectyCube on React Native

### ISSUE THREAD

**Issue by michelepapale1996** [ConnectyCube/connectycube-js-samples#20]
Hi, I'm trying to using push notifications using ConnectyCube on React Native. Main problem is that if I send a notification from the admin panel of ConnectyCube (or from source code), the admin panel says that the notification has been successfully delivered, but nothing happens on the android emulator. Maybe someone can think that there are some bugs client-side in the implementation of my onMessageListener:

    notificationListener = firebase.notifications().onNotification((notification) => {
        console.log("Hi!")
    });

Anyway, if I try to send a notification through the Firebase console, all works and I receive the notification. Can you help me?

**Comment by DaveLomber** [comment]
hey @michelepapale1996 

I do not remember if Android Emulators support push notifications, so it's better to try on a real device 

Could you please post here the whole code snippet on how you subscribe to push notifications on ConnectyCube,

will help us to identify what is wrong

thanks

**Comment by michelepapale1996** [comment]
Hi @DaveLomber, 
I've tried, as you suggested, on a real device and, again, sending a notification from connectycube didn't work, while sending from Firebase did. Here the code snippet to subscribe: 
```
firebase.messaging().getToken().then(token => {
      var params = {
            notification_channel: 'gcm',
            device: {
                  platform: 'android',
                  udid: token
             },
             push_token: {
                  environment: 'development',
                  client_identification_sequence: token
              }
       };
        ConnectyCubeHandler.getInstance().pushnotifications.subscriptions.create(params, 
              function(error, result){});
})

**Comment by DaveLomber** [comment]
Hi @michelepapale1996 

Let's check the following things:
1) go to Admin panel, Users module, choose this user, what's device subscription this user has?
Is there this development subscription?
2) When you send a push from API or Admin panel - do you choose a development env? It should be the same as you use for subscribe
3) Also, when send from Admin panel, then you can go to Queue tab and check the status of a push (delivered/failed). What's the status here?

**Comment by michelepapale1996** [comment]
1. As you can see, the user has correctly the device subscription:
![image](https://user-images.githubusercontent.com/9197981/53560832-9764d880-3b4d-11e9-8a97-9eec68d6b615.png)
![image](https://user-images.githubusercontent.com/9197981/53560865-a64b8b00-3b4d-11e9-8772-a9bb27cac3ce.png)

2 and 3. I choose development env:
![image](https://user-images.githubusercontent.com/9197981/53560985-e7439f80-3b4d-11e9-907b-d3d421e3b6fa.png)
![image](https://user-images.githubusercontent.com/9197981/53561010-f9bdd900-3b4d-11e9-89a1-8c21dc4363d7.png)

and this is the log of the message: 
`{"notification":{"id":9972,"badge":null,"device_token":null,"sound":"default","alert":null,"data":{"message":"bkb","collapse_key":"event9386"},"expiry":86400,"delivered":true,"delivered_at":"2019-02-28T02:16:31+00:00","failed":null,"failed_at":null,"fail_after":"2019-02-28T03:16:31+00:00","retries":0,"error_code":null,"error_description":null,"deliver_after":null,"alert_is_json":null,"app_id":167,"collapse_key":null,"delay_while_idle":false,"registration_ids":["da_nBodRbjw:APA91bFmn2IvYaZaMaH0gTxAqfVBwaKr0Gi4IJZc48ojx0nXaB6o0nM7QPi7TZKHenXMssa2bAhxvVNlp2vHUONbG1FSCp1rLDSIacO8fokufHt97tb4bZno0_lUrNGs-AbC0T26-nYF","c9uvYKei1wI:APA91bEIMsQ7p_e2fRemaXhygkSw-iMoZJi5e7Gbuof7LkaYDac69lEu27CAEJLS8G70--bw_D3ilAzM9ChrAxWmhYOPLjlt6QooTCBo9lYgYmM0tighnxooOrFaTWKyjacBqJO-VAQC","ePFPI7ViH04:APA91bGpY6TisfsBEJ5HJ9fLMiecpk6V_NJ9xaxXitQZ7QkfRnNB_zDFHVAen1QQ4f85-qllJHDwmi1G9CK2Fp864lbHiVlGfTJB1RDgXcMvJdKMDHQzE-N_kfudKFcdjTYeQy6ty3n7"],"uri":null,"priority":10,"url_args":null,"category":null,"content_available":false,"mutable_content":false,"notification":null,"type":"Rpush::Client::Redis::Gcm::Notification","event_id":9386,"event_date":"2019-02-28T02:16:30+00:00"},"log":[{"device_token":null,"delivered_at":"2019-02-28T02:16:31+00:00","failed_at":null,"error_code":null,"error_description":null}]}`

As you can see, all seems to work fine, but I don't receive any notification on the phone.

**Comment by DaveLomber** [comment]
@michelepapale1996 do you use this package for pushes?
https://github.com/zo0r/react-native-push-notification

**Comment by michelepapale1996** [comment]
@DaveLomber no, I'm using react-native-firebase and, as listener, 
firebase.notifications().onNotification()

**Comment by DaveLomber** [comment]
@michelepapale1996 seems you are using a wrong method 

https://rnfirebase.io/docs/v5.x.x/notifications/introduction

> The React Native Firebase Notifications Module deals with notification-only and notification + data FCM remote messages. 
> For data-only FCM messages please see the Messaging module.

As ConnectyCube sends a data push messages, then please try to use Messaging module:

https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages

**Comment by michelepapale1996** [comment]
Hi @DaveLomber, you're right! I was using a wrong method. Really thank you for you help! :)
