### ISSUE TITLE
React Native (android & ios) 1-1 chat with history demo

### ISSUE THREAD

**Issue by yadav-durgesh** [ConnectyCube/connectycube-js-samples#21]
Hi, I wanted React Native (android & ios both) 1-1 chat and chat history demo, to integrate into my project without Expo(detached). If present please provide me the link or info about it.

**Comment by DaveLomber** [comment]
You asked we delivered ;-DD 
 
https://github.com/ConnectyCube/connectycube-js-samples/tree/master/SampleChatRN
