### ISSUE TITLE
help integrating video call sample into Cordova app

### ISSUE THREAD

**Issue by kotthoff** [ConnectyCube/connectycube-js-samples#30]
Would love getting help building the example but in my app.

**Comment by DaveLomber** [comment]
Hi @kotthoff , thanks for contacting us 

we have a video calling sample for JS browser environment
and here is a guide on how to convert it for Cordova env

https://developers.connectycube.com/js/code-samples-videochat-cordova  , both Android & iOS

Let me know if it helps you or you have any issues - we are happy to assist

**Comment by DaveLomber** [comment]
@kotthoff please let us know if you need any help
