### ISSUE TITLE
getUserMedia errTypeError: peer.addTrack is not a function in React Native Video Chat 

### ISSUE THREAD

**Issue by shubham-2710** [ConnectyCube/connectycube-js-samples#31]
![Capture](https://user-images.githubusercontent.com/37359938/56198060-bfee5680-6057-11e9-9d86-bbc6d26ea65c.PNG)

Hi,
Thanks for providing the React native Video Sample, I am trying to run the sample app with Debugger On.
It gets stuck with an error as below getUserMedia errTypeError: peer.addTrack is not a function(attached is an image).

Without debugger on, the video call happens.

**Comment by DaveLomber** [comment]
Hi @shubham-2710 
thanks for reporting

so it works good w/o debugger attached, but if you enable a remote debugger via Chrome then it fails, correct?

**Comment by shubham-2710** [comment]
Yup, that's correct.

**Comment by DaveLomber** [comment]
@shubham-2710 iOS or Android ?

**Comment by DaveLomber** [comment]
@shubham-2710  while we are investigating this
Could you please expand the error and provide a full screenshot with a stacktrace and lines numbers

**Comment by DaveLomber** [comment]
@shubham-2710 we have a clue why it can happen
Could you please check one thing 

do `console.log("navigator.userAgent", navigator.userAgent)` in your app and post here an output

**Comment by DaveLomber** [comment]
@shubham-2710 ok great !
