### ISSUE TITLE
[video call] _JStoXML internal bug and stream doesn't close automatically

### ISSUE THREAD

**Issue by lherman-cs** [ConnectyCube/connectycube-js-samples#32]
I have a couple of issues with the video calling api:

# _JStoXML and _XMLtoJS internal bugs

I was trying to pass custom user data to `session.call`. But, the _JStoXML converter seemed to not work properly. The message should be:

```xml
...
<userInfo>
    ...
   <bandwidth>0</bandwidth>
</userInfo>
```

But, it instead converted to:

```xml
...
</userInfo>
<bandwidth>0</bandwidth>
```

After debugging it, I saw that there is a bug in `cubeChatInternalUtil.js` on line 142.  `msg.c(title)` should be `msg = msg.c(title)`.

After this, the format looks correct as shown in the example, https://developers.connectycube.com/server/videochat. 

But, the bug seems more than that. Because, when I tested the change, the receiver got an error saying that there's a malformed xml format. And, I inspected that there's no handler for `userInfo`. 

# Streams don't close automatically through the callback

let say we have 2 users, Alice and Bob, talking through the video calling service.

When Alice stops the call, Alice's local and remote streams close automatically because it calls `session.stop` which will later call internal `_stop` which will clean up everything. But, Bob's local streams and remote streams are still intact. If I call `session.stop` on Bob's side, it'll give an error saying `Ignore 'onStop', there is no information about session `, which is from `cubeWebRTCClient.js` on line 267.

**Note: I've tested the example code, and it also suffers the same problems.**

**Comment by lherman-cs** [comment]
@DaveLomber I figured to create a new issue instead of extending the old one.

**Comment by DaveLomber** [comment]
@lherman-cs thanks for reporting this
we will check and get back to you asap

**Comment by DaveLomber** [comment]
Just a quick update: #1 is fixed, working on #2

**Comment by DaveLomber** [comment]
@lherman-cs  both issue are fixed in this commit
https://github.com/ConnectyCube/connectycube-js-samples/commit/dae3ce30c300b23a3bc32e7def8c21e0e3b2a8c5 

Please use a new SDK upgrade connectycube-reactnative-1.7.3.tgz which is available here https://github.com/ConnectyCube/connectycube-js-samples/blob/master/RNVideoChat/connectycube-reactnative-1.7.3.tgz at master branch 

Please let us know about your feedback

**Comment by DaveLomber** [comment]
@lherman-cs SDK 1.7.3 is released and Video code sample is updated to use it
All is verified at our end

Please let us know if you face anything else and need any help
