### ISSUE TITLE
how to get data from the session

### ISSUE THREAD

**Issue by jekanok** [ConnectyCube/connectycube-js-samples#33]
at node.js?

**Comment by DaveLomber** [comment]
@jekanok 
here is a link on how to do it 
https://developers.connectycube.com/js/authentication-and-users?id=create-session-token 

```
ConnectyCube.createSession(function(error, session) {

});


var userCredentials = {login: 'cubeuser', password: 'awesomepwd'};
ConnectyCube.createSession(userCredentials, function(error, session) {

});
```

here you have an access to a `session` object

**Comment by DaveLomber** [comment]
@jekanok let us know if you have any other issues
