### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_this7.socket.write')]

### ISSUE THREAD

**Issue by KOKAProduktion** [ConnectyCube/connectycube-js-samples#39]
Hi guys!

And it's me again :)

Another issue i'm facing integrating your example code (especially https://github.com/ConnectyCube/connectycube-js-samples/tree/master/RNChat) into an existing app, is probably the most critical one...

When submitting a message via the Chat UI (RNChat/src/components/ChatScreen/index.js) "nothing" happens. I'm afraid there's an issue with the socket initialization inside the XMPP library.

Console output:

[Unhandled promise rejection: TypeError: null is not an object (evaluating '_this7.socket.write')]
- node_modules\@xmpp\connection\index.js:330:18 in <unknown>
- node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo
- ... 14 more stack frames from framework internals

This is actually obstructing usage the most. May i ask you if you have experienced similar issues like this? Could it be a dependency issue?

I have to add, that i'm not building from scratch so i had to modify the redux store connections in the examples. Maybe it's an issue with the dispatch order messed up?

Any shared insights or hints would be very helpful.
Thank you in advance and cheers!

**Comment by KOKAProduktion** [comment]
Sorry, i forgot to provide some environment info:

- RN with redux/saga/reselect inside non-detached Expo app
- react-native-router-flux used in the examples combined on top of target apps react-navigation (showing warning but both navigations appear to work correctly)
- manually connected the example to existing redux/saga store

package.json dependencies:

    "@babel/runtime": "^7.4.3",
    "connectycube-reactnative": "^1.7.3",
    "expo": "^31.0.6",
    "immutable": "^4.0.0-rc.12",
    "intl": "^1.2.5",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "react": "16.5.0",
    "react-intl-native": "^2.1.2",
    "react-moment": "^0.7.9",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-autogrow-textinput": "^5.2.0",
    "react-native-device-info": "^1.7.0",
    "react-native-elements": "^1.0.0-beta",
    "react-native-expo-image-cache": "^3.2.0",
    "react-native-fontawesome": "^6.0.1",
    "react-native-htmlview": "^0.14.0",
    "react-native-i18n": "^2.0.15",
    "react-native-image-picker": "^0.27.0",
    "react-native-keyboard-aware-scroll-view": "^0.7.2",
    "react-native-modal": "^6.5.0",
    "react-native-popup-menu": "^0.14.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-set-soft-input-mode": "^1.0.3",
    "react-navigation": "^2.18.2",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-immutable": "^4.0.0",
    "redux-saga": "^1.0.2",
    "reduxsauce": "^1.1.0",
    "rn-prompt": "^1.0.4",
    "tcomb-form-native": "^0.6.16"

Thanks again for the great software and have a nice weekend!
Cheers!

**Comment by simologos** [comment]
Hi, I'm facing the exact same issue, my dependencies are very similar:
    ```
"connectycube-reactnative": "^1.7.3",
    "expo": "^32.0.0",
    "firebase": "^6.1.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-calendars": "^1.32.0",
    "react-native-device-info": "^2.0.1",
    "react-native-material-menu": "^0.6.0",
    "react-native-push-notification": "^3.1.3",
    "react-native-tags": "^2.0.0",
    "react-navigation": "^3.8.1",
    "react-redux": "6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.0.2"
```

I also tried to send a message without using redux-saga (directly from the react component).

CallStack is:
```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_this7.socket.write')]
- node_modules\@xmpp\connection\index.js:330:18 in <unknown>
- node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo
- node_modules\promise\setimmediate\core.js:200:23 in doResolve
- node_modules\promise\setimmediate\core.js:66:12 in Promise
- node_modules\@xmpp\connection\index.js:322:23 in write
- node_modules\@xmpp\connection\index.js:304:24 in proceed
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in <unknown>
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:152:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:200:17 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:464:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:320:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:17 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

Surprisingly `ConnectyCube.chat.send` returns a new message ID, but the message does not reach the server.

Any help would be much appreciated,
Simon
Any help

**Comment by DaveLomber** [comment]
Hi @simologos 
we use the lib in many of apps already, but we do not face anything like this

couple questions to clarify:

You face it in a standard RNChat code sample w/o any modifications? 
Or you moved some parts from sample into your own app and then face it?

**Comment by simologos** [comment]
Hi @DaveLomber 
Thanks for your answer and sorry for my late response.
I moved some parts from the sample to by expo based app.

I was able to work arround the send issue by simply calling the REST API directly.

But it seems XMPP is not working with expo.
I also don't get any events about new messages..

No errors, no nothing, the handler simply does not get called. And I did it exactly like in the sample app.
Do you have any sample code for building a connectycube chat app with expo?

**Comment by simologos** [comment]
On thing I need to mention, I am using Firebase Phone Auth.
And by checking the SDK Code, I see that cubeChat.js uses username and password for the xmpp client in react native:

`
...} else if (Utils.getEnv().reactnative) {
            self.xmppClient = XMPPClient.client({
                service: Config.chatProtocol.websocket,
                credentials: function authenticate(auth, mechanism) {
                    var crds = {
                        username: self.xmppClient.cbUserName,
                        password: self.xmppClient.cbUserPassword
                    };
                    return auth(crds);
                }
            });
        }
`

Could this be a problem?

**Comment by DaveLomber** [comment]
@simologos initially this sample was built own top of Expo 
but then we ejected it because of push notification lib we use in the sample not working under Expo. 
So it worked well before, with Expo 

One question  - did you call `connect` to chat before sending messages and successfully receive a response callback ?

**Comment by simologos** [comment]
@DaveLomber 
You where exactly right! stupid me... sorry that I wasted your time.
Sending and receiving messages is now working!
Thank you very much for your help!

**Comment by DaveLomber** [comment]
@simologos great!
no worries  man
let us know if you need anything else
